### PR TITLE
added textfield component

### PR DESCRIPTION
**Pull request by andrew-levy**

### CODE REVIEW

**Comment by badsyntax** [comment]
Do you plan on making the TextField controllable?

**Comment by andrew-levy** [comment]
> Do you plan on making the TextField controllable?

@badsyntax  It should be a controlled input the way I have it set up. You use react state to control the text. Or am I misunderstanding? Lmk what you envision the api looking like.

**Comment by badsyntax** [comment]
I oculd be missing something! (not very familiar with jetpack) but in your example in `App.tsx`, this doesn't appear to be working:

```tsx
<Button
    text="Default"
    onClick={() => {
      setText("Updated Text");
    }}
  />
```

It seems like state is

**Comment by andrew-levy** [comment]
Ah okay, that's probably just a bug. I basically was just getting all components to "work" and now im going to focus on getting them to work well

**Pull request merged**
